In [24]:
import pandas as pd

In [25]:
data = pd.read_excel('Metricos CDI_2026.xlsx', header=1, usecols= lambda x: 'unamed' not in str(x).lower())

In [26]:
data

,Proceso,Numero de Metrico,Nombre del Metrico,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE,RESULTADO 2026,Limite Amarillo,Limite Verde
0,C04,1030.0,Average number of Claim per month,2.000,1.000,5.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,1.416667,1.25
1,C03,1080.0,PPAP validated on time according to customer P...,100.000,100.000,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.333333,100.000000,100.00
2,C04,1095.0,Daily Service Rate (OTD Negociado),99.000,99.800,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.233333,96.466667,99.00
3,C04,1100.0,Number of PPAP validated under deviation,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.000000,0.95
4,C04,1140.0,Number of customer line stoppage,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.083333,0.00
5,S01,1200.0,Supplier Service Rate (otd),100.000,100.000,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.333333,99.916667,99.95
6,P01,1401.0,EBITDA,338.000,267.000,220.000,244.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.083333,302.583333,NaN
7,S01,1402.0,Net Purchase index,97.940,97.800,97.100,98.750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.6325,93.979167,97.00
8,P01,1403.0,NCFD,-404.000,223.000,-484.000,-138.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-66.916667,358.833333,NaN
9,S01,1422.0,Number of customer claim due to supplier failure,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.083333,0.00
10,S10,2040.0,Absence rate A1,2.100,2.090,3.000,3.580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8975,2.168333,2.00
11,S10,2041.0,Absence rate (ADT) Injustificadas,0.580,0.830,0.740,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.229167,0.634167,0.55
12,P02,2050.0,Number of occupationnal incidents,0.000,0.000,1.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.083333,0.250000,0.00
13,P02,2055.0,Number of Almost Incident,4.000,4.000,6.000,4.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,3.000000,4.00
14,S10,2080.0,Rotation Rate,5.320,4.140,4.500,6.850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.734167,5.307500,4.60
15,S10,2090.0,Training plan achievement rate,132.430,139.220,148.520,148.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.3775,88.352500,92.00
16,C02,2401.0,Number of new customer,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,1.00
17,C02,2402.0,Number of customer visit,8.000,6.000,6.000,6.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.166667,6.000000,8.00
18,C02,2403.0,Quantity of RFQ Received per year,13.000,48.000,22.000,61.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20.000000,25.00
19,C02,2404.0,RFQ in Demo target Market declined,4.000,4.000,0.000,27.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.916667,3.000000,2.50
20,C02,2405.0,Awarded turnover,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,606.708333,1000.00
21,C02,2410.0,Number of intitial offer answered to Customer,6.000,41.000,28.000,32.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.916667,20.000000,25.00
22,P02,2412.0,Occupationnal Incident frequence rate (acumulada),0.000,0.000,20.400,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,5.683333,0.00
23,P02,2413.0,Occupationnal Incident Severity rate (Tasa de ...,0.000,0.000,0.060,0.140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.016667,0.066667,0.00
24,P02,2430.0,Electric Consumption per plastic tons transformed,432.000,444.000,503.000,442.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.75,525.000000,500.00
25,P02,2431.0,Sold waste ratio/ waste created,68.000,0.000,18.380,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.198333,72.666667,82.00
26,C02,2432.0,Past due for Tooling due to refused PPAP,127.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.583333,31.083333,10.00
27,P02,2433.0,Waste disposal cost/ production value,0.088,0.313,0.487,0.354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1035,0.058942,0.06
28,C04,4010.0,Number of Improvment idea per Year per person,0.140,0.190,0.410,0.250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0825,0.181667,0.18
29,C04,4011.0,Number of GRP closed per year,12.000,19.000,21.000,23.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.25,13.333333,15.00
30,C04,4015.0,Realized accepted improvment idea rate (Kaizen),256.000,246.000,187.000,152.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.083333,167.000000,180.00
31,C04,4030.0,CNQ,8.720,8.900,10.140,9.810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.130833,9.610833,8.50
32,C04,4031.0,CNQ AIR BAGS,7.880,7.630,5.990,6.020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.293333,7.811667,6.00
33,C04,4032.0,CNQ HIGH GLOSS,15.730,15.920,17.300,16.240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4325,18.977500,16.00
34,C04,4033.0,Percentage of scrap at Injection,0.260,0.240,0.690,0.210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.116667,0.345833,0.32
35,C04,4034.0,Percentage of scrap metallic paint,11.030,11.420,12.930,7.440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.568333,14.019167,12.50
36,C04,4035.0,CNQ LOW GLOSS,4.610,5.540,6.650,5.680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.873333,7.204167,6.00
37,C04,4036.0,SCRAP LOW GLOSS,4.250,5.130,6.170,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.545833,3.930000,3.30
38,C04,4050.0,Injection TRP,90.380,86.600,87.530,90.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.593333,89.847500,91.00
39,C04,4051.0,Assy TRP,63.000,63.000,62.000,66.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.166667,64.666667,67.00
40,C04,4052.0,Paint TRP,63.000,62.000,64.500,66.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.333333,63.541667,68.00
41,P01,4060.0,BFR PIEZAS,-453.000,-358.000,528.000,789.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.166667,-0.383333,NaN
42,P01,4061.0,BFR TOOLING,1562.000,1328.000,1264.000,1252.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450.5,26.458333,NaN
43,P01,4070.0,Added Value per employee,20.700,19.460,18.000,18.650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.400833,19.265000,21.00
44,S01,4080.0,Number of Supplier Claim officialized,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.250000,0.20
45,C04,4210.0,Number of customer logistic Claim,0.000,0.000,0.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.083333,0.166667,0.00
46,C04,4270.0,Late paiment from customer (tooling excluded),6.100,6.100,7.500,12.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.708333,3.554167,2.50
47,S09,4360.0,Preventiv maintenance performed rate equipement,92.000,94.000,94.000,94.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.166667,90.333333,91.00
48,S09,4361.0,MTBF Injection,23.160,115.000,110.000,143.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.5975,151.385833,180.00
49,S09,4362.0,MTBF Peinture,373.000,32.000,356.000,237.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.233333,438.514167,525.00
50,S09,4366.0,MTTR Injection,0.650,0.270,0.260,0.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123333,0.481667,0.45
51,S09,4367.0,MTTR peinture,0.300,0.180,0.250,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0775,0.325833,0.30
52,S09,4370.0,Rate of production down time due tool faiulre,0.080,3.170,0.810,0.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.38,0.405000,0.35
53,S09,4372.0,Repetitive failure on the same mold,0.000,3.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,0.166667,0.15
54,P01,4380.0,Target rate fullfilled,60.600,52.900,47.600,50.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.641667,68.475000,70.00
55,C04,4413.0,Injection TRS,56.000,52.000,55.000,56.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.25,45.995833,50.00
56,C04,4414.0,Painting TRS,61.000,60.000,59.000,61.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.083333,57.687500,60.00
57,C04,4415.0,Painting TRS skyline,60.000,60.000,68.000,66.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.166667,58.000000,60.00
58,C04,4416.0,Assembly TRS,62.000,61.000,60.000,62.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.416667,61.966667,65.00
59,C04,4432.0,Number of claim repetition,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000,0.00
60,C04,4433.0,Number of A claim,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000,0.00
61,P01,4435.0,LPA audit planning fullfilement,100.000,100.000,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.333333,96.783333,98.00
62,S06,4440.0,IT Issues,2.000,0.000,0.000,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.416667,1.000000,1.00
63,S05,4450.0,Number of calibration done within the planned ...,100.000,100.000,100.000,77.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.416667,100.000000,100.00
64,C04,4470.0,Number of internal claim created and treated w...,2.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166667,0.250000,0.25
65,C04,4490.0,Rate of Raw Material Stock,32.000,33.500,34.100,35.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.225,27.010000,NaN
66,C04,4491.0,Rate of stock of Raw material Vs. Sales,10.500,10.440,12.600,9.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.595,9.775000,NaN
67,C04,4500.0,Rate of Stock of Finish Goods+WIP,13.000,15.200,15.470,12.540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.684167,6.532500,NaN
68,C04,4502.0,Rate of Finish Good Only,7.700,10.200,7.310,7.120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.694167,3.760833,NaN
69,C04,4504.0,Obsolescence Cost,0.000,10492.000,3910.000,3918.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1526.666667,4488.264167,4000.00
70,S01,4510.0,Premium Freight in,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,593.866667,500.00
71,C04,4511.0,Premium Freight Out,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5090.833333,3000.00
72,P02,4610.0,Weight Waste Ratio (Waste tonnage/Raw material...,18.046,41.610,33.756,28.374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.148833,26.010000,23.00
73,C03,4740.0,Project transferred to production according to...,100.000,100.000,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.333333,0.000000,0.00
74,C03,5030.0,Gate review done on time ratio (+/- 1 week),96.000,94.000,90.000,96.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.333333,97.083333,98.00
75,C03,5040.0,Monthly margin Followup/ deviation to initial ...,92.000,95.000,93.000,93.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.083333,98.163333,98.20
76,S06,5090.0,Internet Shutdown,0.000,0.000,0.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166667,0.500000,0.45
77,S09,9403.0,MTBF Assemblage,2969.000,2699.000,1484.000,1484.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,719.733333,2482.000000,2550.00
78,S09,9406.0,MTTR Assemblage,0.190,0.180,0.180,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0625,0.192500,0.19
79,S10,10401.0,Open Position filling rate,0.000,0.000,100.000,100.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.666667,39.285833,45.00
80,S10,10403.0,Number of recruiting failure,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,20.833333,16.00
81,S10,10432.0,Training satisfaction rate just after 1 week,93.020,93.000,93.840,94.780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.22,91.954167,91.95
82,S10,10433.0,Training satisfaction rate just after 3 month,92.800,89.000,96.000,90.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.666667,90.105000,90.11
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total 86 metricos,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44 metricos verde,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14 Metricos amarillo,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22 Metricos rojo,NaN,NaN

In [27]:
new_data = data[['Proceso','Nombre del Metrico', 'Numero de Metrico', 'Limite Amarillo', 'Limite Verde']].copy()

In [28]:
new_data

,Proceso,Nombre del Metrico,Numero de Metrico,Limite Amarillo,Limite Verde
0,C04,Average number of Claim per month,1030.0,1.416667,1.25
1,C03,PPAP validated on time according to customer P...,1080.0,100.000000,100.00
2,C04,Daily Service Rate (OTD Negociado),1095.0,96.466667,99.00
3,C04,Number of PPAP validated under deviation,1100.0,1.000000,0.95
4,C04,Number of customer line stoppage,1140.0,0.083333,0.00
5,S01,Supplier Service Rate (otd),1200.0,99.916667,99.95
6,P01,EBITDA,1401.0,302.583333,NaN
7,S01,Net Purchase index,1402.0,93.979167,97.00
8,P01,NCFD,1403.0,358.833333,NaN
9,S01,Number of customer claim due to supplier failure,1422.0,0.083333,0.00
10,S10,Absence rate A1,2040.0,2.168333,2.00
11,S10,Absence rate (ADT) Injustificadas,2041.0,0.634167,0.55
12,P02,Number of occupationnal incidents,2050.0,0.250000,0.00
13,P02,Number of Almost Incident,2055.0,3.000000,4.00
14,S10,Rotation Rate,2080.0,5.307500,4.60
15,S10,Training plan achievement rate,2090.0,88.352500,92.00
16,C02,Number of new customer,2401.0,0.500000,1.00
17,C02,Number of customer visit,2402.0,6.000000,8.00
18,C02,Quantity of RFQ Received per year,2403.0,20.000000,25.00
19,C02,RFQ in Demo target Market declined,2404.0,3.000000,2.50
20,C02,Awarded turnover,2405.0,606.708333,1000.00
21,C02,Number of intitial offer answered to Customer,2410.0,20.000000,25.00
22,P02,Occupationnal Incident frequence rate (acumulada),2412.0,5.683333,0.00
23,P02,Occupationnal Incident Severity rate (Tasa de ...,2413.0,0.066667,0.00
24,P02,Electric Consumption per plastic tons transformed,2430.0,525.000000,500.00
25,P02,Sold waste ratio/ waste created,2431.0,72.666667,82.00
26,C02,Past due for Tooling due to refused PPAP,2432.0,31.083333,10.00
27,P02,Waste disposal cost/ production value,2433.0,0.058942,0.06
28,C04,Number of Improvment idea per Year per person,4010.0,0.181667,0.18
29,C04,Number of GRP closed per year,4011.0,13.333333,15.00
30,C04,Realized accepted improvment idea rate (Kaizen),4015.0,167.000000,180.00
31,C04,CNQ,4030.0,9.610833,8.50
32,C04,CNQ AIR BAGS,4031.0,7.811667,6.00
33,C04,CNQ HIGH GLOSS,4032.0,18.977500,16.00
34,C04,Percentage of scrap at Injection,4033.0,0.345833,0.32
35,C04,Percentage of scrap metallic paint,4034.0,14.019167,12.50
36,C04,CNQ LOW GLOSS,4035.0,7.204167,6.00
37,C04,SCRAP LOW GLOSS,4036.0,3.930000,3.30
38,C04,Injection TRP,4050.0,89.847500,91.00
39,C04,Assy TRP,4051.0,64.666667,67.00
40,C04,Paint TRP,4052.0,63.541667,68.00
41,P01,BFR PIEZAS,4060.0,-0.383333,NaN
42,P01,BFR TOOLING,4061.0,26.458333,NaN
43,P01,Added Value per employee,4070.0,19.265000,21.00
44,S01,Number of Supplier Claim officialized,4080.0,0.250000,0.20
45,C04,Number of customer logistic Claim,4210.0,0.166667,0.00
46,C04,Late paiment from customer (tooling excluded),4270.0,3.554167,2.50
47,S09,Preventiv maintenance performed rate equipement,4360.0,90.333333,91.00
48,S09,MTBF Injection,4361.0,151.385833,180.00
49,S09,MTBF Peinture,4362.0,438.514167,525.00
50,S09,MTTR Injection,4366.0,0.481667,0.45
51,S09,MTTR peinture,4367.0,0.325833,0.30
52,S09,Rate of production down time due tool faiulre,4370.0,0.405000,0.35
53,S09,Repetitive failure on the same mold,4372.0,0.166667,0.15
54,P01,Target rate fullfilled,4380.0,68.475000,70.00
55,C04,Injection TRS,4413.0,45.995833,50.00
56,C04,Painting TRS,4414.0,57.687500,60.00
57,C04,Painting TRS skyline,4415.0,58.000000,60.00
58,C04,Assembly TRS,4416.0,61.966667,65.00
59,C04,Number of claim repetition,4432.0,0.000000,0.00
60,C04,Number of A claim,4433.0,0.000000,0.00
61,P01,LPA audit planning fullfilement,4435.0,96.783333,98.00
62,S06,IT Issues,4440.0,1.000000,1.00
63,S05,Number of calibration done within the planned ...,4450.0,100.000000,100.00
64,C04,Number of internal claim created and treated w...,4470.0,0.250000,0.25
65,C04,Rate of Raw Material Stock,4490.0,27.010000,NaN
66,C04,Rate of stock of Raw material Vs. Sales,4491.0,9.775000,NaN
67,C04,Rate of Stock of Finish Goods+WIP,4500.0,6.532500,NaN
68,C04,Rate of Finish Good Only,4502.0,3.760833,NaN
69,C04,Obsolescence Cost,4504.0,4488.264167,4000.00
70,S01,Premium Freight in,4510.0,593.866667,500.00
71,C04,Premium Freight Out,4511.0,5090.833333,3000.00
72,P02,Weight Waste Ratio (Waste tonnage/Raw material...,4610.0,26.010000,23.00
73,C03,Project transferred to production according to...,4740.0,0.000000,0.00
74,C03,Gate review done on time ratio (+/- 1 week),5030.0,97.083333,98.00
75,C03,Monthly margin Followup/ deviation to initial ...,5040.0,98.163333,98.20
76,S06,Internet Shutdown,5090.0,0.500000,0.45
77,S09,MTBF Assemblage,9403.0,2482.000000,2550.00
78,S09,MTTR Assemblage,9406.0,0.192500,0.19
79,S10,Open Position filling rate,10401.0,39.285833,45.00
80,S10,Number of recruiting failure,10403.0,20.833333,16.00
81,S10,Training satisfaction rate just after 1 week,10432.0,91.954167,91.95
82,S10,Training satisfaction rate just after 3 month,10433.0,90.105000,90.11
83,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN

In [29]:
clean_data = new_data.dropna()

In [34]:
clean_data

,Proceso,Nombre del Metrico,Numero de Metrico,Limite Amarillo,Limite Verde
0,C04,Average number of Claim per month,1030.0,1.416667,1.25
1,C03,PPAP validated on time according to customer P...,1080.0,100.000000,100.00
2,C04,Daily Service Rate (OTD Negociado),1095.0,96.466667,99.00
3,C04,Number of PPAP validated under deviation,1100.0,1.000000,0.95
4,C04,Number of customer line stoppage,1140.0,0.083333,0.00
5,S01,Supplier Service Rate (otd),1200.0,99.916667,99.95
7,S01,Net Purchase index,1402.0,93.979167,97.00
9,S01,Number of customer claim due to supplier failure,1422.0,0.083333,0.00
10,S10,Absence rate A1,2040.0,2.168333,2.00
11,S10,Absence rate (ADT) Injustificadas,2041.0,0.634167,0.55
12,P02,Number of occupationnal incidents,2050.0,0.250000,0.00
13,P02,Number of Almost Incident,2055.0,3.000000,4.00
14,S10,Rotation Rate,2080.0,5.307500,4.60
15,S10,Training plan achievement rate,2090.0,88.352500,92.00
16,C02,Number of new customer,2401.0,0.500000,1.00
17,C02,Number of customer visit,2402.0,6.000000,8.00
18,C02,Quantity of RFQ Received per year,2403.0,20.000000,25.00
19,C02,RFQ in Demo target Market declined,2404.0,3.000000,2.50
20,C02,Awarded turnover,2405.0,606.708333,1000.00
21,C02,Number of intitial offer answered to Customer,2410.0,20.000000,25.00
22,P02,Occupationnal Incident frequence rate (acumulada),2412.0,5.683333,0.00
23,P02,Occupationnal Incident Severity rate (Tasa de ...,2413.0,0.066667,0.00
24,P02,Electric Consumption per plastic tons transformed,2430.0,525.000000,500.00
25,P02,Sold waste ratio/ waste created,2431.0,72.666667,82.00
26,C02,Past due for Tooling due to refused PPAP,2432.0,31.083333,10.00
27,P02,Waste disposal cost/ production value,2433.0,0.058942,0.06
28,C04,Number of Improvment idea per Year per person,4010.0,0.181667,0.18
29,C04,Number of GRP closed per year,4011.0,13.333333,15.00
30,C04,Realized accepted improvment idea rate (Kaizen),4015.0,167.000000,180.00
31,C04,CNQ,4030.0,9.610833,8.50
32,C04,CNQ AIR BAGS,4031.0,7.811667,6.00
33,C04,CNQ HIGH GLOSS,4032.0,18.977500,16.00
34,C04,Percentage of scrap at Injection,4033.0,0.345833,0.32
35,C04,Percentage of scrap metallic paint,4034.0,14.019167,12.50
36,C04,CNQ LOW GLOSS,4035.0,7.204167,6.00
37,C04,SCRAP LOW GLOSS,4036.0,3.930000,3.30
38,C04,Injection TRP,4050.0,89.847500,91.00
39,C04,Assy TRP,4051.0,64.666667,67.00
40,C04,Paint TRP,4052.0,63.541667,68.00
43,P01,Added Value per employee,4070.0,19.265000,21.00
44,S01,Number of Supplier Claim officialized,4080.0,0.250000,0.20
45,C04,Number of customer logistic Claim,4210.0,0.166667,0.00
46,C04,Late paiment from customer (tooling excluded),4270.0,3.554167,2.50
47,S09,Preventiv maintenance performed rate equipement,4360.0,90.333333,91.00
48,S09,MTBF Injection,4361.0,151.385833,180.00
49,S09,MTBF Peinture,4362.0,438.514167,525.00
50,S09,MTTR Injection,4366.0,0.481667,0.45
51,S09,MTTR peinture,4367.0,0.325833,0.30
52,S09,Rate of production down time due tool faiulre,4370.0,0.405000,0.35
53,S09,Repetitive failure on the same mold,4372.0,0.166667,0.15
54,P01,Target rate fullfilled,4380.0,68.475000,70.00
55,C04,Injection TRS,4413.0,45.995833,50.00
56,C04,Painting TRS,4414.0,57.687500,60.00
57,C04,Painting TRS skyline,4415.0,58.000000,60.00
58,C04,Assembly TRS,4416.0,61.966667,65.00
59,C04,Number of claim repetition,4432.0,0.000000,0.00
60,C04,Number of A claim,4433.0,0.000000,0.00
61,P01,LPA audit planning fullfilement,4435.0,96.783333,98.00
62,S06,IT Issues,4440.0,1.000000,1.00
63,S05,Number of calibration done within the planned ...,4450.0,100.000000,100.00
64,C04,Number of internal claim created and treated w...,4470.0,0.250000,0.25
69,C04,Obsolescence Cost,4504.0,4488.264167,4000.00
70,S01,Premium Freight in,4510.0,593.866667,500.00
71,C04,Premium Freight Out,4511.0,5090.833333,3000.00
72,P02,Weight Waste Ratio (Waste tonnage/Raw material...,4610.0,26.010000,23.00
73,C03,Project transferred to production according to...,4740.0,0.000000,0.00
74,C03,Gate review done on time ratio (+/- 1 week),5030.0,97.083333,98.00
75,C03,Monthly margin Followup/ deviation to initial ...,5040.0,98.163333,98.20
76,S06,Internet Shutdown,5090.0,0.500000,0.45
77,S09,MTBF Assemblage,9403.0,2482.000000,2550.00
78,S09,MTTR Assemblage,9406.0,0.192500,0.19
79,S10,Open Position filling rate,10401.0,39.285833,45.00
80,S10,Number of recruiting failure,10403.0,20.833333,16.00
81,S10,Training satisfaction rate just after 1 week,10432.0,91.954167,91.95
82,S10,Training satisfaction rate just after 3 month,10433.0,90.105000,90.11

In [30]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [31]:
clean_data

,Proceso,Nombre del Metrico,Numero de Metrico,Limite Amarillo,Limite Verde
0,C04,Average number of Claim per month,1030.0,1.416667,1.25
1,C03,PPAP validated on time according to customer P...,1080.0,100.000000,100.00
2,C04,Daily Service Rate (OTD Negociado),1095.0,96.466667,99.00
3,C04,Number of PPAP validated under deviation,1100.0,1.000000,0.95
4,C04,Number of customer line stoppage,1140.0,0.083333,0.00
5,S01,Supplier Service Rate (otd),1200.0,99.916667,99.95
7,S01,Net Purchase index,1402.0,93.979167,97.00
9,S01,Number of customer claim due to supplier failure,1422.0,0.083333,0.00
10,S10,Absence rate A1,2040.0,2.168333,2.00
11,S10,Absence rate (ADT) Injustificadas,2041.0,0.634167,0.55
12,P02,Number of occupationnal incidents,2050.0,0.250000,0.00
13,P02,Number of Almost Incident,2055.0,3.000000,4.00
14,S10,Rotation Rate,2080.0,5.307500,4.60
15,S10,Training plan achievement rate,2090.0,88.352500,92.00
16,C02,Number of new customer,2401.0,0.500000,1.00
17,C02,Number of customer visit,2402.0,6.000000,8.00
18,C02,Quantity of RFQ Received per year,2403.0,20.000000,25.00
19,C02,RFQ in Demo target Market declined,2404.0,3.000000,2.50
20,C02,Awarded turnover,2405.0,606.708333,1000.00
21,C02,Number of intitial offer answered to Customer,2410.0,20.000000,25.00
22,P02,Occupationnal Incident frequence rate (acumulada),2412.0,5.683333,0.00
23,P02,Occupationnal Incident Severity rate (Tasa de ...,2413.0,0.066667,0.00
24,P02,Electric Consumption per plastic tons transformed,2430.0,525.000000,500.00
25,P02,Sold waste ratio/ waste created,2431.0,72.666667,82.00
26,C02,Past due for Tooling due to refused PPAP,2432.0,31.083333,10.00
27,P02,Waste disposal cost/ production value,2433.0,0.058942,0.06
28,C04,Number of Improvment idea per Year per person,4010.0,0.181667,0.18
29,C04,Number of GRP closed per year,4011.0,13.333333,15.00
30,C04,Realized accepted improvment idea rate (Kaizen),4015.0,167.000000,180.00
31,C04,CNQ,4030.0,9.610833,8.50
32,C04,CNQ AIR BAGS,4031.0,7.811667,6.00
33,C04,CNQ HIGH GLOSS,4032.0,18.977500,16.00
34,C04,Percentage of scrap at Injection,4033.0,0.345833,0.32
35,C04,Percentage of scrap metallic paint,4034.0,14.019167,12.50
36,C04,CNQ LOW GLOSS,4035.0,7.204167,6.00
37,C04,SCRAP LOW GLOSS,4036.0,3.930000,3.30
38,C04,Injection TRP,4050.0,89.847500,91.00
39,C04,Assy TRP,4051.0,64.666667,67.00
40,C04,Paint TRP,4052.0,63.541667,68.00
43,P01,Added Value per employee,4070.0,19.265000,21.00
44,S01,Number of Supplier Claim officialized,4080.0,0.250000,0.20
45,C04,Number of customer logistic Claim,4210.0,0.166667,0.00
46,C04,Late paiment from customer (tooling excluded),4270.0,3.554167,2.50
47,S09,Preventiv maintenance performed rate equipement,4360.0,90.333333,91.00
48,S09,MTBF Injection,4361.0,151.385833,180.00
49,S09,MTBF Peinture,4362.0,438.514167,525.00
50,S09,MTTR Injection,4366.0,0.481667,0.45
51,S09,MTTR peinture,4367.0,0.325833,0.30
52,S09,Rate of production down time due tool faiulre,4370.0,0.405000,0.35
53,S09,Repetitive failure on the same mold,4372.0,0.166667,0.15
54,P01,Target rate fullfilled,4380.0,68.475000,70.00
55,C04,Injection TRS,4413.0,45.995833,50.00
56,C04,Painting TRS,4414.0,57.687500,60.00
57,C04,Painting TRS skyline,4415.0,58.000000,60.00
58,C04,Assembly TRS,4416.0,61.966667,65.00
59,C04,Number of claim repetition,4432.0,0.000000,0.00
60,C04,Number of A claim,4433.0,0.000000,0.00
61,P01,LPA audit planning fullfilement,4435.0,96.783333,98.00
62,S06,IT Issues,4440.0,1.000000,1.00
63,S05,Number of calibration done within the planned ...,4450.0,100.000000,100.00
64,C04,Number of internal claim created and treated w...,4470.0,0.250000,0.25
69,C04,Obsolescence Cost,4504.0,4488.264167,4000.00
70,S01,Premium Freight in,4510.0,593.866667,500.00
71,C04,Premium Freight Out,4511.0,5090.833333,3000.00
72,P02,Weight Waste Ratio (Waste tonnage/Raw material...,4610.0,26.010000,23.00
73,C03,Project transferred to production according to...,4740.0,0.000000,0.00
74,C03,Gate review done on time ratio (+/- 1 week),5030.0,97.083333,98.00
75,C03,Monthly margin Followup/ deviation to initial ...,5040.0,98.163333,98.20
76,S06,Internet Shutdown,5090.0,0.500000,0.45
77,S09,MTBF Assemblage,9403.0,2482.000000,2550.00
78,S09,MTTR Assemblage,9406.0,0.192500,0.19
79,S10,Open Position filling rate,10401.0,39.285833,45.00
80,S10,Number of recruiting failure,10403.0,20.833333,16.00
81,S10,Training satisfaction rate just after 1 week,10432.0,91.954167,91.95
82,S10,Training satisfaction rate just after 3 month,10433.0,90.105000,90.11

In [33]:
clean_data.to_csv('output.csv', index=False)

In [35]:
excel_ids = set(data["Numero de Metrico"].dropna().astype(int))

In [36]:
print(len(excel_ids))
print(sorted(excel_ids))

83
[1030, 1080, 1095, 1100, 1140, 1200, 1401, 1402, 1403, 1422, 2040, 2041, 2050, 2055, 2080, 2090, 2401, 2402, 2403, 2404, 2405, 2410, 2412, 2413, 2430, 2431, 2432, 2433, 4010, 4011, 4015, 4030, 4031, 4032, 4033, 4034, 4035, 4036, 4050, 4051, 4052, 4060, 4061, 4070, 4080, 4210, 4270, 4360, 4361, 4362, 4366, 4367, 4370, 4372, 4380, 4413, 4414, 4415, 4416, 4432, 4433, 4435, 4440, 4450, 4470, 4490, 4491, 4500, 4502, 4504, 4510, 4511, 4610, 4740, 5030, 5040, 5090, 9403, 9406, 10401, 10403, 10432, 10433]

In [39]:
clean_data[[
    "Numero de Metrico",
    "Limite Amarillo",
    "Limite Verde"
]].to_csv('output.csv', index=False)